### ISSUE TITLE
Relationship Tab Blank

### ISSUE THREAD

**Issue by JangeL1997** [edbmods/EdBPrepareCarefully#259] opened 2019-06-04 05:39 UTC
Relationship tab after i click add the next page is blank
![123451](https://user-images.githubusercontent.com/39123849/58853841-1712be00-86ce-11e9-81a1-c10f9da1bef3.JPG)
![1234124](https://user-images.githubusercontent.com/39123849/58853894-4c1f1080-86ce-11e9-960e-27432d59e548.JPG)

**Comment by edbmods** [comment] 2019-07-18 00:45
I'm not able to reproduce the same problem with a new game.  Do you have any other mods installed?  Are you starting with a new set of characters or are you working off of a preset?  Do you know how to get and post the game's log file?

**Comment by edbmods** [comment] 2020-02-29 19:44
Closing this issue.  It applies to an old version and there isn't enough additional information to reproduce.  Please re-open it if you see it happening in a 1.1 version of the mod.

**Closed by edbmods** 2020-02-29 19:44 UTC
Labels: cannot reproduce
