### ISSUE TITLE
PrepareCarefully dosent work no matter what i do

### ISSUE THREAD

**Issue by DenkoGamer** [edbmods/EdBPrepareCarefully#251] opened 2018-11-12 23:04 UTC
wuy does the 1.0 version not work on my 1.0 version of my game but my 0.19 version but whit this version on the 1.0 game some things just dont work like dont open at all if i click on them but i mean at least it opens the mods main menu apart from the 1.0 version that says that there was a problem whit opening the mod menu and its not because of a mod or a saved game because i reseted my entire game fresh so i wouldent have any mods or worlds and it did the same thing and when i deactivate or activate the mod it dosent give me an error log so this is all i could find
![01ed7a2e7f2803b85889f589d33fac43f0eb170078f86640da2937d1656ea242](https://user-images.githubusercontent.com/44306429/48380324-9b243a80-e6d7-11e8-8fc0-c1990984a8c7.png)

**Comment by edbmods** [comment] 2019-07-21 21:33
I know that this issue does happen for some people, and it's not clear to me what is causing it.  I cannot reproduce.  Starting with a fresh install of the game and only this mod installed is a helpful place to start, but without more information--error logs, for example--there is not much I can do.

**Comment by edbmods** [comment] 2020-02-29 19:45
Closing this issue.  It applies to an old version and there isn't enough additional information to reproduce.  Please re-open it if you see it happening in a 1.1 version of the mod.

**Closed by edbmods** 2020-02-29 19:45 UTC
Labels: cannot reproduce, need more info
