### ISSUE TITLE
I click prepare carefully and nothing happens

### ISSUE THREAD

**Issue by explosion56** [edbmods/EdBPrepareCarefully#203] opened 2017-11-28 21:35 UTC
when I click the prepare carefully button it doesn't do anything

**Comment by chaos17** [comment] 2018-08-21 14:25
I've the same problem since I installed mods to add new races:
https://i.imgur.com/vDSUR3A.png

**Comment by edbmods** [comment] 2019-07-18 00:36
I tried with the mods listed in the above comment--at least all of the ones that are still compatible with RimWorld 1.0--and I cannot reproduce the problem.  Closing for now.  Reopen if you're still having the same issue and if you can narrow down the problem to a smaller set of mods.

**Closed by edbmods** 2019-07-18 00:36 UTC
