### ISSUE TITLE
Update 1.4??

### ISSUE THREAD

**Issue by Bonnie7489** [edbmods/EdBPrepareCarefully#321] opened 2022-10-23 13:43 UTC
@edbmods 
Hi just want to ask if this i going to get update to 1.4

Love the mod.

**Comment by Unga-bunga69** [comment] 2022-10-23 20:52
Let's hope so but it takes time because the new update adds ALOT of character variations and effects and the dev(s) have to make sure that everything they add doesn't mess with the base game or other mods. That being said it will take some time but lets hope it gets updated soon.

**Comment by emmahyde** [comment] 2022-10-24 03:28
Would love to know if this is planned.

**Comment by alonske** [comment] 2022-10-25 04:25
> If an update is not forthcoming, is anyone able to fork this, do some updating, and perhaps maintain it until we get our original author back?

I'm kinda poking at it in my downtime, but I'm not a modder, game dev, or .NET dev. More of a learning exercise for me. If anyone who's a bit more committed than me wants to get a bit of a head start on some of the low hanging fruit, you can see my fork here. https://github.com/alonske/EdBPrepareCarefully

**Comment by shootex20** [comment] 2022-10-28 05:42
> > If an update is not forthcoming, is anyone able to fork this, do some updating, and perhaps maintain it until we get our original author back?
> 
> I'm kinda poking at it in my downtime, but I'm not a modder, game dev, or .NET dev. More of a learning exercise for me. If anyone who's a bit more committed than me wants to get a bit of a head start on some of the low hanging fruit, you can see my fork here. https://github.com/alonske/EdBPrepareCarefully
> 
> Update: ~currently at the point where editor is working and create custom pawns, critical flaw though, they don't spawn in when you try jump into game : -( Made a lot of progress tho~
> 
> pawns spawning in now, up to point of fixing bugs I'm encountering while using the UI. Issues around childhood backstories, random ideoligion button, a little bit of strangeness surrounding babies and newborn body types, maybe some spiciness with gender settings but I don't wanna delve into that, skin colour buttons do nothing.

I am going to try and jump in this, I'm definitely not a pro Modder by any means but I can help sort out some of the issues after work / free time. I did fork your repo as well :)

**Comment by alonske** [comment] 2022-10-29 23:13
I noticed there's a workshop page for the fork I made. Because that fork is getting a bit of attention I'm just providing a bit of an update of where I'm at with the fork.

Still just using it to learn some C#, OOP and just generally developing in a windows environment. There will come a point that I won't update that repo anymore and it  won't be feature complete, bug free, or even have feature parity with the 1.3 version.

To understand the kind of bugs I've been looking at up till this point - I really went in there with a hatchet to get the project to build and that broke a lot of things, it's those things that I've been trying to fix to get it up to speed with the 1.3 version. I think I fixed a lot of things in that category, but I've also exhausted a lot of my easy wins.

So for anyone interested in the progress of that fork, feel free to open pull requests to it, I've been merging them regularly. When I next take a look at it I'm going to take a quick look at the prosthetics system for the sake of mechanitors, then pause on fixing regressions for a minute for my own sanity and maybe look at some xenotype stuff.

I haven't at all tested any of the preset loading stuff, but some of the changes I got the preset loaders to build I doubt are working. This is a low priority for me

I also haven't tested any alien race stuff but I can near guarantee you that it's going to be broken, I don't use that mod so I probably won't look into fixing that compatibility.

**Comment by AMeyerInkSoft** [comment] 2022-11-02 00:11
I've been daydreaming of updating this mod lately, but I just don't have the leftover energy to contribute in my spare time.  I am both appreciative and envious of the people who are willing and able to commit time to working on this mod or fork it, etc.  This mod is the sort of thing that makes me look forward to retirement, supposing I don't work myself to death before then.

**Comment by daPhipz** [comment] 2022-12-27 15:45
An update for 1.4 was released today: https://github.com/edbmods/EdBPrepareCarefully/releases/tag/v1.4.2

**Closed** 2024-04-26 05:03 UTC
