### ISSUE TITLE
Error log when I Hit the randomize dice for Backstory

### ISSUE THREAD

**Issue by Lyndai** [edbmods/EdBPrepareCarefully#198] opened 2017-11-20 23:02 UTC
I was making a crash landing group, everything was working fine. Didn't have an age up issue (14 to 24). But I was testing the randomize buttons. It works for the avatar, traits, and name, but I got this when I clicked on it for the backstory, does it every time:

```
Exception` filling window for EdB.PrepareCarefully.Page_PrepareCarefully: System.NullReferenceException: Object reference not set to an instance of an object
  at EdB.PrepareCarefully.ControllerPawns.RandomizeBackstories () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) EdB.PrepareCarefully.PanelBackstory/RandomizeBackstoriesHandler:invoke_void__this__ ()
  at EdB.PrepareCarefully.PanelBackstory.DrawPanelContent (EdB.PrepareCarefully.State state) [0x00000] in <filename unknown>:0 
  at EdB.PrepareCarefully.PanelBase.Draw (EdB.PrepareCarefully.State state) [0x00000] in <filename unknown>:0 
  at EdB.PrepareCarefully.TabViewPawns.Draw (EdB.PrepareCarefully.State state, Rect rect) [0x00000] in <filename unknown>:0 
  at EdB.PrepareCarefully.Page_PrepareCarefully.DoWindowContents (Rect inRect) [0x00000] in <filename unknown>:0 
  at Verse.Window+<WindowOnGUI>c__AnonStorey0.<>m__0 (Int32 x) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

```

**Comment by edbmods** [comment] 2017-11-21 02:43
Thanks for the bug report.  It turns out that Issue #195, Issue #199 and this one are all caused by the same problem.  It will be fixed in the next release.

**Closed** 2017-11-21 03:17 UTC
Labels: duplicate
